// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IReclaimVerifier$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IReclaimVerifier";
  readonly sourceName: "contracts/IReclaimVerifier.sol";
  readonly abi: [{"inputs":[{"components":[{"components":[{"internalType":"string","name":"provider","type":"string"},{"internalType":"string","name":"parameters","type":"string"},{"internalType":"string","name":"context","type":"string"}],"internalType":"struct ClaimInfo","name":"claimInfo","type":"tuple"},{"components":[{"components":[{"internalType":"bytes32","name":"identifier","type":"bytes32"},{"internalType":"address","name":"owner","type":"address"},{"internalType":"uint32","name":"timestampS","type":"uint32"},{"internalType":"uint32","name":"epoch","type":"uint32"}],"internalType":"struct CompleteClaimData","name":"claim","type":"tuple"},{"internalType":"bytes[]","name":"signatures","type":"bytes[]"}],"internalType":"struct SignedClaim","name":"signedClaim","type":"tuple"}],"internalType":"struct Proof","name":"proof","type":"tuple"}],"name":"verifyProof","outputs":[],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/IReclaimVerifier.sol";
  readonly buildInfoId: "solc-0_8_20-ddccee04daece4e773b4fb4547024aea3926184c";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IReclaimVerifier"]: IReclaimVerifier$Type;
    ["contracts/IReclaimVerifier.sol:IReclaimVerifier"]: IReclaimVerifier$Type;
  }
}